#!/usr/bin/env python3
"""Generate the binary sample files (PNG and DOCX) used to try the GUI.

They are built here rather than committed so that the repository carries no
opaque binaries. Both files are minimal but genuinely valid, and both carry the
kind of AI-provenance metadata the engine looks for.

    python3 examples/make-binary-examples.py
"""

from __future__ import annotations

import struct
import zipfile
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    return (
        struct.pack(">I", len(payload))
        + kind
        + payload
        + struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF)
    )


def write_png(path: Path, width: int = 16, height: int = 16) -> None:
    """A tiny solid-colour PNG carrying tEXt metadata that names an AI tool."""
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    # One filter byte per row, then RGB pixels.
    raw = b"".join(b"\x00" + bytes([0x2F, 0x5F, 0xD0]) * width for _ in range(height))

    text_chunks = b"".join(
        _png_chunk(b"tEXt", key + b"\x00" + value)
        for key, value in (
            (b"Software", b"SampleDiffusion 1.0"),
            (b"Comment", b"Generated by an AI image model"),
            (b"Author", b"watermarks-remover-gui example"),
        )
    )

    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", header)
        + text_chunks
        + _png_chunk(b"IDAT", zlib.compress(raw, 9))
        + _png_chunk(b"IEND", b"")
    )


ZWSP = "​"
NBSP = " "

_DOCUMENT_XML = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t xml:space="preserve">This paragraph hides{ZWSP} a zero-width space.</w:t></w:r></w:p>
    <w:p><w:r><w:t xml:space="preserve">And this one uses a no-break{NBSP}space.</w:t></w:r></w:p>
  </w:body>
</w:document>
"""

_CORE_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties
    xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
    xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:title>Sample document</dc:title>
  <dc:creator>Generated by an AI assistant</dc:creator>
  <cp:lastModifiedBy>SampleModel 2.0</cp:lastModifiedBy>
</cp:coreProperties>
"""

_APP_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>SampleModel 2.0</Application>
  <Company>watermarks-remover-gui example</Company>
</Properties>
"""

_CONTENT_TYPES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
"""

_ROOT_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>
"""


def write_docx(path: Path) -> None:
    """A minimal but valid DOCX with AI markers in both text and properties."""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", _CONTENT_TYPES)
        archive.writestr("_rels/.rels", _ROOT_RELS)
        archive.writestr("word/document.xml", _DOCUMENT_XML)
        archive.writestr("docProps/core.xml", _CORE_XML)
        archive.writestr("docProps/app.xml", _APP_XML)


def main() -> None:
    write_png(HERE / "sample-marked.png")
    write_docx(HERE / "sample-marked.docx")
    for name in ("sample-marked.png", "sample-marked.docx"):
        print(f"wrote {HERE / name}")


if __name__ == "__main__":
    main()
